name: Set environment cache
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: macos-latest
    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r-binary@v2
        with:
          r-version: '4.3.2'
          
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install system dependencies
        run: |
          brew install gdal udunits
          
      - name: Add cached R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-4.3.2-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-4.3.2-
            
      - name: Install R packages
        run: |
          install.packages(c(
            "tidyverse", "stringr", "janitor", "readr", "dplyr",
            "sf", "leaflet", "htmlwidgets", "leaflet.providers",
            "leaflet.extras", "lubridate", "htmltools"
          ), repos = "https://cloud.r-project.org")
        shell: Rscript {0}
