name: Set environment cache

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: /Users/runner/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}
          restore-keys: ${{ runner.os }}-brew-

      - name: Update Homebrew
        run: brew update

      - name: Install Homebrew dependencies
        run: |
          brew bundle --file=Brewfile

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Add cached R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R packages
        run: Rscript -e 'install.packages(c("tidyverse","stringr","janitor","readr","dplyr","sf","leaflet","htmlwidgets","leaflet.providers","leaflet.extras","htmltools"))'