name: Update R Wildfire Map

on:
  schedule:
    - cron: '15 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: macos-latest
    timeout-minutes: 120  # Increase the timeout to 2 hours

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unlink conflicting pkg-config
      run: |
        brew unlink pkg-config@0.29.2

    - name: Install system dependencies
      run: |
        brew install gdal
        brew install udunits
        brew install pandoc

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("stringr", "leaflet", "leaflet.extras", "leaflet.providers", "sf", "htmlwidgets", "htmltools", "janitor", "lubridate"))'

    - name: Run R script
      run: |
        Rscript scripts/wildfires_scrape_build.R  # Adjusted path to the script

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Update data and map'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}