on:
  schedule:
    - cron: '30 0/1 * * *'
  workflow_dispatch:

name: Wildfire data map rebuild

jobs:
  render:
    name: Get fire data
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Packages cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
      - name: Rebuild fire data map
        run: Rscript scripts/wildfires_scrape_build.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Wildfires data updated!' || echo "No changes"
          git push origin || echo "No changes to commit"
          
