on:
  schedule:
    - cron: '20 0/1 * * *'
  workflow_dispatch:
name: Wildfire data map rebuild
jobs:
  render:
    name: Get fire data
    runs-on: macos-latest
    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Packages cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}-1  # Match cache version
          restore-keys: |
            ${{ runner.os }}-r-
            
      - name: Verify R packages
        run: |
          pkg_list <- c("tidyverse", "stringr", "janitor", "readr", "dplyr",
                       "sf", "leaflet", "htmlwidgets", "leaflet.providers",
                       "leaflet.extras", "lubridate", "htmltools")
          missing <- pkg_list[!pkg_list %in% installed.packages()[,"Package"]]
          if(length(missing) > 0) {
            install.packages(missing, repos = "https://cloud.r-project.org")
          }
        shell: Rscript {0}
        
      - name: Rebuild fire data map
        run: Rscript scripts/wildfires_scrape_build.R
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Wildfires data updated!' || echo "No changes"
          git push origin || echo "No changes to commit"
