on:
  schedule:
    - cron: '20 0/1 * * *'
  workflow_dispatch:

name: Wildfire data map rebuild

jobs:
  render:
    name: Get fire data
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          install-r: true
          remove-openmp-macos: true
          http-user-agent: default
          use-public-rspm: false
          Ncpus: 1

      - name: Restore cached Homebrew packages
        uses: actions/cache@v3
        with:
          path: /usr/local/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}-${{ runner.arch }}
          restore-keys: ${{ runner.os }}-brew-

      - name: Restore cached R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}-${{ runner.arch }}
          restore-keys: ${{ runner.os }}-r-

      - name: Rebuild fire data map
        run: Rscript scripts/wildfires_scrape_build.R

      - name: Commit results
        run: |
          git add -A
          git commit -m 'Wildfires data updated!' || echo "No changes"
          git push origin || echo "No changes to commit"